application: tutoring-intro-programming
version: 1
runtime: python
api_version: 1

handlers:
- url: /deckjs
  static_dir: deckjs

- url: /prettify
  static_dir: prettify

- url: /intro
  static_dir: intro
  
- url: /.*
  script: index.py

builtins:
- datastore_admin: on